export {default as Account} from "./Account.js";
export {default as Home} from "./Home.js";
export {default as Inbox} from "./Inbox";
export {default as Login} from "./Login.js";
export {default as Logout} from "./Logout.js";
export {default as MyPosts} from "./MyPosts.js";
export {default as NewPost} from "./NewPost.js";
export {default as Posts} from  "./Posts.js";
export {default as Register} from "./Register.js";
export {default as SendMessage} from "./SendMessage.js"